apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  selector:
    app: Selector Label
  type: LoadBalancer | ClusterIP | NodePort
  ports:
    - port: 11211
      targetPort: vpromc-port
